/**
 * Raw district data from the maps-data.json static snapshot.
 *
 * One row per district per projection year: the snapshot carries the whole
 * quinquennial series, so `geometry_id` repeats across years and only the pair
 * `(ano, geometry_id)` is unique.
 */
export type DistrictData = {
  /** Projection year these counts describe. */
  ano: number;
  /** SEADE district code (80001-80096 for the capital's 96 districts). */
  cod_distr: number;
  nome: string;
  municipio: string;
  /** Feature id of the district's polygon in `public/distrito-municipal-v2.geojson`. */
  geometry_id: number;
  count_65_69: number;
  count_70_74: number;
  count_75plus: number;
  /** Residents of every age — the denominator of the share-of-total series. */
  total: number;
};

/**
 * Raw shape of the maps-data.json static snapshot generated by
 * `scripts/generateMapsData.ts` from the SEADE projection CSV in
 * `src/data-source-static/data/raw/`.
 */
export type StaticMapsDataSource = {
  districts: DistrictData[];
};

/**
 * One point from a `data/points/<layer>.json` static snapshot — a GeoSampa
 * facility or stop with its WGS84 coordinates and the district it falls in.
 */
export type PointData = {
  /** Sequential id assigned by `scripts/generatePointsData.ts`, in CSV order. */
  id: number;
  longitude: number;
  latitude: number;
  /** District name, computed point-in-polygon against the district geometry. */
  distrito: string;
  /**
   * The CSV's descriptive columns, as-is (`nome`, `tipo`, `esfera`, ...). They
   * differ per layer; `nome` is the one every layer carries.
   */
  atributos: Record<string, string>;
};

/**
 * Raw shape of a point-layer snapshot generated by
 * `scripts/generatePointsData.ts` from a GeoSampa CSV in
 * `src/data-source-static/data/raw/`.
 */
export type StaticPointsDataSource = {
  points: PointData[];
};

/**
 * One subprefeitura from the subprefeituras.json static snapshot, with the
 * project districts it groups.
 */
export type SubprefeituraData = {
  /** GeoSampa's `cd_identificador_subprefeitura` (1–32); also the feature id in `public/subprefeituras.geojson`. */
  id: number;
  /** The city's own two-digit code (`cd_subprefeitura`). */
  codigo: string;
  sigla: string;
  /** Display name, accented (the source spells it in unaccented capitals). */
  nome: string;
  /** One of the city's five regions (Norte, Sul, Leste, Oeste, Centro). */
  regiao: string;
  /** `geometry_id`s of the districts it groups, ascending. */
  distritos: number[];
};

/**
 * Raw shape of the subprefeituras.json static snapshot generated by
 * `scripts/generateSubprefeituras.ts` from GeoSampa.
 */
export type StaticSubprefeiturasDataSource = {
  subprefeituras: SubprefeituraData[];
};

/** A GeoJSON polygon geometry, in WGS84. */
export type PolygonGeometryData =
  | { type: 'Polygon'; coordinates: [number, number][][] }
  | { type: 'MultiPolygon'; coordinates: [number, number][][][] };

/** One park from the `data/polygons/parques.json` static snapshot. */
export type ParkData = {
  /** Sequential id assigned by `scripts/generateParksData.ts`. */
  id: number;
  nome: string;
  /** Parque Urbano, Parque Linear, Parque Orla, Parque Natural… */
  categoria: string;
  /** The park's code in the city's park registry (CADPARCS), when it has one. */
  cadparc: string;
  geometry: PolygonGeometryData;
};

/**
 * Raw shape of the parks snapshot generated by `scripts/generateParksData.ts`
 * from GeoSampa.
 */
export type StaticParksDataSource = {
  parques: ParkData[];
};
